### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by boyang9602** [tsantalis/RefactoringMiner#105]
Hi, an exception occurred when I used it to detect refactorings on https://github.com/apache/cassandra/commit/666a00089cb40f8d84f2974070b18c0744acbb9b:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:101)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:325)
	at rfdetector.App.main(App.java:43)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:2457)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1164)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:128)
	at gr.uom.java.xmi.diff.UMLClassDiff.createBodyMappers(UMLClassDiff.java:108)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:105)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:147)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:140)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:96)
	... 2 more
```

**Comment by tsantalis** [comment]
@boyang9602 The commit you give in the link does not contain Java code.
The modified file is `doc/source/cql/ddl.rst`
I am unable to replicate the exception.

**Comment by boyang9602** [comment]
It looks weird. When I use `detectAll` API, it will throw an exception and crash at commit 666a00089cb40f8d84f2974070b18c0744acbb9b. But when I use `detectBetweenCommits(repo, "commitBeforeIt", "commitAfterIt")` and `detectAtCommit`, nothing happens. Let me find a reproducing waty.

**Comment by boyang9602** [comment]
Ok, it's this commit: https://github.com/GLZ9568/cassandra/commit/beb9658dd5e18e3a6a4e8431b6549ae4c33365a9
