### ISSUE TITLE
Problem with fetching data directly from GitHub

### ISSUE THREAD

**Issue by shehan** [tsantalis/RefactoringMiner#110]
Do you have a sample (standalone) project that demonstrates fetching data directly from GitHub? I created a new project, added version 2.0.2 libraries from Maven, created a personal GitHub access token (gave all repo permissions), and used the [sample code on RefactoringMiner readme.](https://github.com/tsantalis/RefactoringMiner#with-all-information-fetched-directly-from-github)

The code compiles, but it throws a NullPointerException 
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:467)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:500)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detectAtCommit$1(GitHistoryRefactoringMinerImpl.java:465)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NullPointerException
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.populateWithGitHubAPI(GitHistoryRefactoringMinerImpl.java:513)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:487)
	... 7 more
```

Any advice on what I'm doing wrong?

**Comment by shehan** [comment]
I was able to resolve the runtime exception; I had placed the "github-oauth.properties" file in the wrong directory.

However, now the issue is that the program runs without returning any output. It does not print the detected refactorings in the console.

**Comment by shehan** [comment]
Alright, I was able to figure out what I did wrong-- the timeout value I gave was too small. Works fine now!

**Comment by tsantalis** [comment]
I am glad you figured out the solution.
