### ISSUE TITLE
StringIndexOutOfBoundsException in UMLType.extractTypeObject()

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#127]
https://github.com/google/guava/commit/8c412a725f91ccf05fc5231ce2cdae99141edc8e
> java.lang.StringIndexOutOfBoundsException: String index out of range: -6
> 	at java.lang.String.substring(String.java:1967)
> 	at gr.uom.java.xmi.UMLType.extractTypeObject(UMLType.java:182)
> 	at gr.uom.java.xmi.UMLType.extractTypeObject(UMLType.java:200)
> 	at gr.uom.java.xmi.UMLType.extractTypeObject(UMLType.java:200)
> 	at gr.uom.java.xmi.decomposition.OperationInvocation.matchesOperation(OperationInvocation.java:194)
> 	at gr.uom.java.xmi.diff.InlineOperationDetection.matchingInvocations(InlineOperationDetection.java:79)
> 	at gr.uom.java.xmi.diff.InlineOperationDetection.check(InlineOperationDetection.java:38)
> 	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForInlinedOperations(UMLClassBaseDiff.java:1642)
> 	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:110)
> 	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:147)
> 	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:144)
> 	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:436)
> 	at org.refactoringminer.test.TestBuilder.assertExpectations(TestBuilder.java:118)
> 	at org.refactoringminer.test.TestAllRefactorings.testAllRefactorings(TestAllRefactorings.java:42)

**Comment by tsantalis** [comment]
The problem is caused in the following type
```java
TypeToken<ForGetSubType.Outer<?>.Sub<?>>
```
