### ISSUE TITLE
NullPointerException occurs if the repository is not cloned locally.

### ISSUE THREAD

**Issue by JintoYamanaka** [tsantalis/RefactoringMiner#161]
I want to use RefactoringMiner from the command line.
When I run:

```
./RefactoringMiner -gc https://github.com/danilofes/refactoring-toy-example.git 36287f7c3b09eff78395267a3ac0d7da067863fd 10
```

the following error occurs.
I used several repositories instead of the toy project, but I still got the same error.

```
log4j:WARN No appenders could be found for logger (org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Error processing commit 36287f7c3b09eff78395267a3ac0d7da067863fd
java.lang.NullPointerException
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.getGitHubRepository(GitHistoryRefactoringMinerImpl.java:742)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.populateWithGitHubAPI(GitHistoryRefactoringMinerImpl.java:581)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:556)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detectAtCommit$1(GitHistoryRefactoringMinerImpl.java:534)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
{
"commits": [
{
	"repository": "https://github.com/danilofes/refactoring-toy-example.git",
	"sha1": "36287f7c3b09eff78395267a3ac0d7da067863fd",
	"url": "https://github.com/danilofes/refactoring-toy-example/commit/36287f7c3b09eff78395267a3ac0d7da067863fd",
	"refactorings": []
}]
}
```

However, When I clone the repository locally and run:

```
./RefactoringMiner -c refactoring-toy-example 36287f7c3b09eff78395267a3ac0d7da067863fd
```

The error doesn't  occur.

**Comment by tsantalis** [comment]
Hi @JintoYamanaka 
When using the `-gc` and `-gp` options you must provide a valid OAuth token in the `github-oauth.properties` file stored in the `bin` folder.
`github-oauth.properties` contains a single line starting with `OAuthToken=`
You will have to add your GitHub OAuth token after `OAuthToken=`
Please let me know if this solves the problem.

**Comment by JintoYamanaka** [comment]
Hi, @tsantalis 

I moved `github-oauth.properties` to `bin` folder and that solved this problem!
Thank you so much!
