### ISSUE TITLE
Unable to save results to json for -bc using command line

### ISSUE THREAD

**Issue by alvintanjianjia** [tsantalis/RefactoringMiner#170]
![Capture](https://user-images.githubusercontent.com/28504408/116774631-8814a900-aa90-11eb-83a6-ec723d4915f0.PNG)

Hi, when running using command line

**Case 1:**
Command: RefactoringMiner -bc refactoring-toy-example f3b628f8f9c71a2cdfa052025c4a1ed78ee4c45d d4bce13a443cf12da40a77c16c1e591f4f985b47

Output: Total count: [Commits: 4, Errors: 0, Refactorings: 6]

**Case 2:**
Command: RefactoringMiner -bc refactoring-toy-example f3b628f8f9c71a2cdfa052025c4a1ed78ee4c45d d4bce13a443cf12da40a77c16c1e591f4f985b47 -json test.json

Output: Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.jgit.lib.Repository.resolve(Repository.java:509)
        at org.eclipse.jgit.lib.Repository.resolve(Repository.java:469)
        at org.refactoringminer.util.GitServiceImpl.createRevsWalkBetweenCommits(GitServiceImpl.java:251)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:500)
        at org.refactoringminer.RefactoringMiner.detectBetweenCommits(RefactoringMiner.java:104)
        at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:35)

Can I get some help regarding this issue?

Thank you.

Regards,
Alvin

**Comment by tsantalis** [comment]
@alvintanjianjia 
Thank you for reporting this issue. It has been fixed.
