### ISSUE TITLE
Change Attribute Type- initializer mappings

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#197]
I think the fix does not work for this commit: 
https://github.com/cloudfoundry/uaa/commit/4653a99a88c49d4b1b680b6592ed39f90de68210

**FIXED** in https://github.com/tsantalis/RefactoringMiner/commit/a86fe2fdf96c4d8c069a3cc3019f029b417bce74

**Comment by ameyaKetkar** [comment]
This fix throws the null pointer exception at:
https://github.com/infinispan/infinispan/commit/a4d998ad29f4567250af7676546797817e50a8b0 

```gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.findAttributeExtractions(VariableReplacementAnalysis.java:273)
at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.<init>(VariableReplacementAnalysis.java:98)
at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getRefactorings(UMLOperationBodyMapper.java:682)
at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:2362)
at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1424)
at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:151)
at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMoves(UMLModelDiff.java:2374)
at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMovesIncludingRemovedAndAddedClasses(UMLModelDiff.java:2187)
at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1580)
at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:149)
at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:490)
at org.refactoringminer.RefactoringMiner.detectAtCommit(RefactoringMiner.java:192)
at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:40)```

**Comment by ameyaKetkar** [comment]
Missed to report the statement mapping for this change attribute type:
https://github.com/apache/ignite/commit/1104ca0fa49be07aeef3ee822d1cc1ecc6b598b5#diff-06d921e4f1031092f8b458aa1b70c931604368baedfe487ac787a5f82968a94bL64

**Comment by ameyaKetkar** [comment]
This is a very interesting scenario I found.  
https://github.com/apache/camel/commit/20e26226107f3133c87d0f5c845e02f824823f69#diff-ad14b9fda2a0634577a55c5f226a5fe27c0b77ef683b85e317965e4c95b4392eL261 

RMiner misses to report these. 
I feel this pattern could be a possible addition to the _composite replacements_.
