### ISSUE TITLE
NullPointerException in VariableReplacementAnalysis.existsConflictingParameterRenameInOperationDiff

### ISSUE THREAD

**Issue by ErikBrendel** [tsantalis/RefactoringMiner#223]
I was running version `d15b2932b1811ee1afd39a8cab9fbda1655f2081` (the HEAD commit from 2021-10-27) of this program, trying to find the refactorings from the `apache/logging-log4j2` project between tag 2.4 and 2.14.1. The program still produced results, but the following error message appeared in between. Maybe it is important?

```
java.lang.NullPointerException
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.existsConflictingParameterRenameInOperationDiff(VariableReplacementAnalysis.java:1788)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.findVariableMerges(VariableReplacementAnalysis.java:961)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.<init>(VariableReplacementAnalysis.java:121)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getRefactorings(UMLOperationBodyMapper.java:1003)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.processMapperRefactorings(UMLClassBaseDiff.java:694)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.getRefactorings(UMLClassBaseDiff.java:559)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1540)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:154)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:109)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:588)
	at org.refactoringminer.RefactoringMiner.detectBetweenCommits(RefactoringMiner.java:108)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:35)
```

**Comment by tsantalis** [comment]
@ErikBrendel 
Do you have from your logs the exact commit where this exception happened?

**Comment by tsantalis** [comment]
The exception is in commit https://github.com/apache/logging-log4j2/commit/3aceb2a327bdade228ec15662bce4cf541f82239

**Comment by ErikBrendel** [comment]
Thank you very much :)
