### ISSUE TITLE
String index out of range: 49

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#24]
Im trying to use your tool to extract refactoring from JHotDraw (https://github.com/wumpz/jhotdraw) after almost 700 refactoring it gives error

java.lang.StringIndexOutOfBoundsException: String index out of range: 49
	at java.lang.String.substring(String.java:1963)
	at gr.uom.java.xmi.diff.MovedClassToAnotherSourceFolder.getRenamePattern(MovedClassToAnotherSourceFolder.java:16)
	at gr.uom.java.xmi.diff.UMLModelDiff.getMoveClassRefactorings(UMLModelDiff.java:671)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:722)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:123)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:82)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:230)
	at example.main(example.java:36)
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 49
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:87)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:230)
	at example.main(example.java:36)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 49
	at java.lang.String.substring(String.java:1963)
	at gr.uom.java.xmi.diff.MovedClassToAnotherSourceFolder.getRenamePattern(MovedClassToAnotherSourceFolder.java:16)
	at gr.uom.java.xmi.diff.UMLModelDiff.getMoveClassRefactorings(UMLModelDiff.java:671)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:722)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:123)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:82)
	... 2 more

**Comment by tsantalis** [comment]
Exception occurs at commit `0cd34f755315dc24bf940779abfec3e58b081ce0`

**Comment by tsantalis** [comment]
The rename pattern is
`jhotdraw7/src/main/java/org/jhotdraw/application`
`jhotdraw7/src/main/java/org/jhotdraw/app`
The exception occurs because there is no common suffix.
In such case, the entire paths should be reported as renamed.
