### ISSUE TITLE
program won't finish

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#246]
Hello, I encountered some cases that the program wouldn't finish. Do you have some solutions? 
This is an example: https://github.com/apache/archiva/commit/f4f7c971b626d04eab567790cbaf6be6418fcaff
And I have encountered a lot of such cases, what shall I do?

https://github.com/apache/archiva/commit/f4f7c971b626d04eab567790cbaf6be6418fcaff [**processing time**: 23 seconds] after commit https://github.com/tsantalis/RefactoringMiner/commit/d5ab1f8911876c29948404cd30d83845e76d4ad3

- [x] archiva
- [x] cassandra
- [x] derby
- [x] drools
- [x] hbase
- [x] hive
- [x] flink

**Comment by tsantalis** [comment]
@victor0624 
Please report all such cases, or as many as you can find from your logs.

**Comment by victor0624** [comment]
The following are some examples. Hope that you may spare some time to help me out.
https://github.com/apache/archiva.git 94fe3a7fc056638c90cbe4a6319c3cb658f395a5 754b2d594076355d6e9d0b7698d309c87a0d672b
https://github.com/apache/cassandra.git 1f91e99223b0d1b7ed8390400d4a06ac08e4aa85 da410153ed250e03080fd48cd0f57baee481412d
https://github.com/apache/derby.git 20d9cee957c322cb5382eab53abe95d4ab37521a 7f3984246d625b811bf2557d75d26835229f747a
https://github.com/kiegroup/drools.git 201b34d26e015f8edf29514635e6e69ec95016c7 97033afa75f0fdfb66ac848fc69a6cc3056b4ec4
https://github.com/apache/hbase.git 948d0cdec4fb35d70404b9b6e27743616400656d 9b7b83d86208c30dbb83ea717e694c5389e71671
https://github.com/apache/hive.git 65da10218eaac25c47a69f6965002a1ac4bfcac3 39d46e8af5a3794f7395060b890f94ddc84516e7
https://github.com/apache/flink.git 3b88e30924268799c96317fe1bf9f5b9c6bf6f80 e5ab4053bb20342699eaa70603b4246845608a89

**Comment by tsantalis** [comment]
@victor0624 
Should I execute those with the `betweenCommits` API.
Do you have the exact commits that failed?

**Comment by victor0624** [comment]
Yes, you should execute them with betweenCommits API.

**Comment by tsantalis** [comment]
2022-04-09 17:40:13 INFO  Processing tmp/cassandra 15955bf03e352e464b8d23c3bc763d2b93643335 ...
2022-04-09 17:40:13 INFO  Processing tmp/cassandra a0c2b2a3809152591d5c5b89fd4b6f1c0a5c9108 ...
2022-04-09 17:40:13 WARN  Ignored revision a0c2b2a3809152591d5c5b89fd4b6f1c0a5c9108 due to error
java.lang.NullPointerException
	at gr.uom.java.xmi.diff.ExtractOperationRefactoring.getRefactoringType(ExtractOperationRefactoring.java:168)
	at gr.uom.java.xmi.diff.ExtractOperationRefactoring.getName(ExtractOperationRefactoring.java:164)
	at gr.uom.java.xmi.diff.ExtractOperationRefactoring.toString(ExtractOperationRefactoring.java:63)
	at gr.uom.java.xmi.diff.UMLModelDiff.filterOutDuplicateRefactorings(UMLModelDiff.java:986)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2052)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:151)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:106)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:635)

**Comment by tsantalis** [comment]
2022-04-09 18:05:19 INFO  Processing tmp/cassandra 438f387705a82ec4d1a3017d74ab38a132ce5476 ...
2022-04-09 18:05:19 INFO  Processing tmp/cassandra b866f81415e160bc7669250e531035b4dc976988 ...
2022-04-09 18:05:19 WARN  Ignored revision b866f81415e160bc7669250e531035b4dc976988 due to error
java.lang.NullPointerException
	at gr.uom.java.xmi.diff.ExtractOperationDetection.createMapperForExtractedMethod(ExtractOperationDetection.java:302)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.processAddedOperation(ExtractOperationDetection.java:121)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.check(ExtractOperationDetection.java:64)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForExtractedOperations(UMLClassBaseDiff.java:1314)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:85)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:150)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:150)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:106)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:635)

**Comment by tsantalis** [comment]
2022-04-10 06:13:24 INFO  Processing tmp/cassandra d9091c5aa88927ee2daa31ec69d865946b975fd9 ...
2022-04-10 06:13:24 INFO  Processing tmp/cassandra bfac864064d19562ed9b50a94af8133fde075ac3 ...
slow commit https://github.com/apache/cassandra/commit/bfac864064d19562ed9b50a94af8133fde075ac3

**Comment by tsantalis** [comment]
2022-04-10 09:11:59 INFO  Processing tmp1/derby 0fe7da6bf5c62e547d417b51eddec3b17ef99ef4 ...
2022-04-10 09:11:59 INFO  Processing tmp1/derby 73e555847f2cb58d2a0e06bd65435953963ecc59 ...
slow commit https://github.com/apache/derby/commit/73e555847f2cb58d2a0e06bd65435953963ecc59 [**processing time**: 6 minutes]

**Comment by tsantalis** [comment]
2022-04-10 13:42:40 INFO  Processing tmp1/drools ad0a5e110debd791cfd0cf386d604daf366f7c45 ...
2022-04-10 13:42:40 INFO  Processing tmp1/drools 95e93b39cf1b15c623cb629d512394cb49920695 ...
slow commit https://github.com/kiegroup/drools/commit/95e93b39cf1b15c623cb629d512394cb49920695

**Comment by tsantalis** [comment]
2022-04-10 21:20:38 INFO  Processing tmp1/hbase 740ed62e500e0f791c75b42f354684777bed9926 ...
2022-04-10 21:20:38 INFO  Processing tmp1/hbase 4d04f853083a2074bb538f87d9bd9938df358c7d ...
slow commit https://github.com/apache/hbase/commit/4d04f853083a2074bb538f87d9bd9938df358c7d

**Comment by tsantalis** [comment]
2022-04-11 10:05:52 INFO  Processing tmp1/hive 96c1dc8bdeaf519fef8aea589dceff16b5793808 ...
2022-04-11 10:05:52 INFO  Processing tmp1/hive d65d5cdeb5f501e361be17754c26e0a96ac319cf ...

**Comment by tsantalis** [comment]
2022-04-17 08:48:18 INFO  Processing tmp1/flink 0afed4dcf9f9639fc90a8f18933be0516b9d7cd3 ...
2022-04-17 08:48:18 INFO  Processing tmp1/flink 5dd42c1ab4dc4d1842ec360d077e1c7c3c6b1981 ...
slow commit https://github.com/apache/flink/commit/5dd42c1ab4dc4d1842ec360d077e1c7c3c6b1981

**Comment by tsantalis** [comment]
2022-04-19 15:09:17 INFO  Processing tmp1/archiva e195adc06c86dafef0353f49993bd836963ce848 ...
2022-04-19 15:09:17 INFO  Processing tmp1/archiva 52bcd1b58bb5ba151c1dc577a649cab9135f2a20 ...
slow commit https://github.com/apache/archiva/commit/52bcd1b58bb5ba151c1dc577a649cab9135f2a20
