### ISSUE TITLE
java.io.FileNotFoundException: github-credentials.properties in repo eduxstad/Signal-Android

### ISSUE THREAD

**Issue by johnxu21** [tsantalis/RefactoringMiner#29]
2018-06-20 12:27:40 WARN  Ignored revision 623bcf9055c11fda5607fb1d9d976471cbbe0a69 due to error
java.io.FileNotFoundException: github-credentials.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:140)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:272)
	at reads.Refactors_MLP_FP.fp(Refactors_MLP_FP.java:78)
	at org.refactoringminer.MLP_FP_Refactoring.main(MLP_FP_Refactoring.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: github-credentials.properties (No such file or directory)
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:162)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:272)
	at reads.Refactors_MLP_FP.fp(Refactors_MLP_FP.java:78)
	at org.refactoringminer.MLP_FP_Refactoring.main(MLP_FP_Refactoring.java:66)
	... 5 more
Caused by: java.io.FileNotFoundException: github-credentials.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:140)
	... 8 more

**Comment by tsantalis** [comment]
When a commit is not found in the locally cloned repository, it will be downloaded from GitHub.
Just make sure to include a valid GitHub username and password in `github-credentials.properties`
