### ISSUE TITLE
A Number of Exceptions

### ISSUE THREAD

**Issue by Ahmadreza-SY** [tsantalis/RefactoringMiner#307]
Hi,

I am working on collecting a large-scale dataset for my research and I use RefactoringMiner as part of the collection. In a minority of use cases (97 among thousands of commits), I faced some exceptions and thought sharing them with you to help you further improve the tool.

Please find the exceptions in the following attached file. Each exception contains the repository URL, the commit, and the exception stack trace.
[RefactoringMinerErrors.log](https://github.com/tsantalis/RefactoringMiner/files/10196554/RefactoringMinerErrors.log)

**Comment by tsantalis** [comment]
Hi @Ahmadreza-SY 
Thank you for reporting these exceptions.
Could you please let me know which version of RefactoringMiner you used?

Thank you,
Nikos

**Comment by Ahmadreza-SY** [comment]
> Hi @Ahmadreza-SY Thank you for reporting these exceptions. Could you please let me know which version of RefactoringMiner you used?
> 
> Thank you, Nikos

I used version 2.3.2

**Comment by tsantalis** [comment]
- [ ] java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.UMLType.getClassType()" because "type" is null
	at gr.uom.java.xmi.diff.UMLModelDiff.conflictingExpression(UMLModelDiff.java:2735)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForExtractedAndMovedOperations(UMLModelDiff.java:2653)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2127)

This exception is already fixed if you use the latest RefactoringMiner commit.
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:151)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:106)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenTags(GitHistoryRefactoringMinerImpl.java:621)

**Comment by tsantalis** [comment]
@Ahmadreza-SY 
I found [3 repeating bugs](https://github.com/tsantalis/RefactoringMiner/issues/307#issuecomment-1344742089) in your log file.
One of them was already fixed, the other two were new bug and were fixed.

If you build RefactoringMiner from the latest commit, you can collect refactorings for these failing commits.

Thank you for reporting these issues. I hope you found the tool useful.
Good luck with your research!

Nikos
