### ISSUE TITLE
RefactoringMiner is not working for all github project.

### ISSUE THREAD

**Issue by jubair0614** [tsantalis/RefactoringMiner#33]
I was trying to collect all refactoring performed in a source code repository such as ( jabref, elasticsearch etc). I got the following error. However, it was working fine for **refactoring-toy-example** project.

`Refactorings at 77d4a9d481d95488f585d697836e9aad03af399e

**Exception in thread "main" java.lang.IllegalAccessError: tried to access class org.eclipse.jdt.core.dom.IDocElement from class gr.uom.java.xmi.UMLModelASTReader**
	at gr.uom.java.xmi.UMLModelASTReader.processTypeDeclaration(UMLModelASTReader.java:119)
	at gr.uom.java.xmi.UMLModelASTReader.processCompilationUnit(UMLModelASTReader.java:107)
	at gr.uom.java.xmi.UMLModelASTReader$1.acceptAST(UMLModelASTReader.java:69)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.parse(CompilationUnitResolver.java:479)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:992)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:72)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:51)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.createModel(GitHistoryRefactoringMinerImpl.java:297)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:125)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:91)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:274)
	at temp.RefMinerTry.main(RefMinerTry.java:137)`

**Comment by tsantalis** [comment]
jabref was processed without any errors.
[jabref.log](https://github.com/tsantalis/RefactoringMiner/files/2280166/jabref.log)
I was not able to replicate the exception using the latest revision of RefactoringMiner.

**Comment by tsantalis** [comment]
elasticsearch was also processed without any errors.
[elasticsearch.log](https://github.com/tsantalis/RefactoringMiner/files/2285243/elasticsearch.log)

**Comment by Symbolk** [comment]
Same problem here, but only happens when running the packaged jar which includes RefactoringMiner.jar.
