### ISSUE TITLE
Refactoring Miner2 crash

### ISSUE THREAD

**Issue by MatinMan** [tsantalis/RefactoringMiner#4]
The Refactoring Miner2 throws an exception when trying to detect refactorings for following  repository:
Project Name: ANTLR4
Source: https://github.com/MatinMan/RefactoringDatasets/tree/ANTLR4
Commit hash: 5587eebd3cb141b6ab10f394bf5ddcd47d86477c
Branch: ANTLR4

Exception Message:
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n].
log4j: Adding appender named [console] to category [root].
2016-07-24 10:48:57 INFO  Checking out antlr4\RefactoringDatasets 5587eebd3cb141b6ab10f394bf5ddcd47d86477c ...
2016-07-24 10:48:58 INFO  Analyzing code after (5587eebd3cb141b6ab10f394bf5ddcd47d86477c) ...
2016-07-24 10:49:02 INFO  Checking out antlr4\RefactoringDatasets b92a642a5781945d02c7d35bebf529c0b473365e ...
2016-07-24 10:49:02 INFO  Analyzing code before (b92a642a5781945d02c7d35bebf529c0b473365e) ...
2016-07-24 10:49:04 WARN  Ignored revision 5587eebd3cb141b6ab10f394bf5ddcd47d86477c due to error
java.lang.UnsupportedOperationException
    at org.refactoringminer.rm2.model.SDEntity.addReferencedBy(SDEntity.java:117)
    at org.refactoringminer.rm2.model.SDType.addReference(SDType.java:114)
    at org.refactoringminer.rm2.analysis.SDModelBuilder.postProcessReferences(SDModelBuilder.java:51)
    at org.refactoringminer.rm2.analysis.SDModelBuilder.analyze(SDModelBuilder.java:123)
    at org.refactoringminer.rm2.analysis.SDModelBuilder.analyzeBefore(SDModelBuilder.java:84)
    at org.refactoringminer.rm2.analysis.GitHistoryStructuralDiffAnalyzer.detectRefactorings(GitHistoryStructuralDiffAnalyzer.java:130)
    at org.refactoringminer.rm2.analysis.GitHistoryStructuralDiffAnalyzer.detectAtCommit(GitHistoryStructuralDiffAnalyzer.java:103)
    at org.refactoringminer.rm2.analysis.GitHistoryRefactoringMiner2.detectAtCommit(GitHistoryRefactoringMiner2.java:64)
    at org.refactoringminer.test.TestBuilder.assertExpectations(TestBuilder.java:115)
    at org.refactoringminer.test.TestRecallKadarDataSet.test(TestRecallKadarDataSet.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Commits: 0  Errors: 1
Total  TP:  0  FP:  0  FN:  0  TN:  0  Unk.:  0  Prec.: NaN  Recall: NaN
error at https://github.com/MatinMan/RefactoringDatasets/commit/5587eebd3cb141b6ab10f394bf5ddcd47d86477c: java.lang.UnsupportedOperationException

**Comment by tsantalis** [comment]
org.refactoringminer.rm2 is no longer part of the project
