### ISSUE TITLE
Stuck at a specific commit

### ISSUE THREAD

**Issue by kavehshahedi** [tsantalis/RefactoringMiner#428]
For the refactorings detection in the [apache/cloudstack](https://github.com/apache/cloudstack) project, the tool was stuck at this specific commit: **83488e01af5789dc3bd3324488c37c0eb4937703**
Link: https://github.com/apache/cloudstack/commit/83488e01af5789dc3bd3324488c37c0eb4937703

Although the `handleException` method was re-implemented, the tool could not ignore this revision and progress the rest commits.

Stack trace (after timeout):
```
org.refactoringminer.api.RefactoringMinerTimedOutException
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:5640)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:3646)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:770)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLClassDiff.processAttributes(UMLClassDiff.java:49)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:100)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:684)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detectAtCommit$3(GitHistoryRefactoringMinerImpl.java:706)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Process finished with exit code 0
```

**Comment by tsantalis** [comment]
@kavehshahedi 
Thank you for your bug report. I will look into it.

**Comment by tsantalis** [comment]
@kavehshahedi 
After the fix it takes around 20 seconds to process this commit
The detected refactorings are:

> Add Method Annotation @SafeVarargs in method public nullIsTrueCallWrapper(call String, args T...) : Boolean from class com.cloud.hypervisor.ovm3.objects.OvmObject
> Add Method Annotation @SafeVarargs in method public nullIsFalseCallWrapper(call String, args T...) : Boolean from class com.cloud.hypervisor.ovm3.objects.OvmObject
> Add Method Annotation @SafeVarargs in method public callWrapper(call String, args T...) : Object from class com.cloud.hypervisor.ovm3.objects.OvmObject
> Add Method Annotation @SafeVarargs in method public nullCallWrapper(call String, nullReturn Boolean, args T...) : Boolean from class com.cloud.hypervisor.ovm3.objects.OvmObject
