### ISSUE TITLE
Error when casting class gr.uom.java.xmi.decomposition.StatementObject

### ISSUE THREAD

**Issue by kavehshahedi** [tsantalis/RefactoringMiner#429]
During the analysis of [apache/hadoop](https://github.com/apache/hadoop), the mentioned commit will throw an exception:
https://github.com/apache/hadoop/commit/b9e3eff62a7415d8666656a75db69ff3e43f8e7e

Stack trace:
```
java.lang.ClassCastException: class gr.uom.java.xmi.decomposition.StatementObject cannot be cast to class gr.uom.java.xmi.decomposition.CompositeStatementObject (gr.uom.java.xmi.decomposition.StatementObject and gr.uom.java.xmi.decomposition.CompositeStatementObject are in unnamed module of loader 'app')
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processInnerNodes(UMLOperationBodyMapper.java:2724)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processInnerNodes(UMLOperationBodyMapper.java:2622)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:334)
	at gr.uom.java.xmi.diff.UMLClassDiff.createBodyMappers(UMLClassDiff.java:152)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:97)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:115)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:534)
```

**Comment by tsantalis** [comment]
@kavehshahedi 

The list of detected refactorings after the fix:

>   Add Attribute Modifier final in attribute private stats : FileSystem.Statistics from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Rename Method private openIfNeeded() : void renamed to private lazySeek(targetPos long, len long) : void in class org.apache.hadoop.fs.s3a.S3AInputStream
>   Change Variable Type e : SocketTimeoutException to e : SocketTimeoutException|SocketException in method public read() : int from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Parameter length : long in method private reopen(targetPos long, length long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Parameter len : long in method private lazySeek(targetPos long, len long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Parameter targetPos : long in method private reopen(targetPos long, length long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Attribute Modifier final in attribute private key : String from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Attribute Modifier final in attribute private contentLength : long from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Extract Method private closeStream(length long) : void extracted from public close() : void in class org.apache.hadoop.fs.s3a.S3AInputStream
>   Change Variable Type e : SocketTimeoutException to e : SocketTimeoutException|SocketException in method public read(buf byte[], off int, len int) : int from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Rename Parameter pos : long to targetPos : long in method public seek(targetPos long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Merge Catch [catch(SocketTimeoutException e), catch(SocketException e)] to catch(SocketTimeoutException|SocketException e) in method public read(buf byte[], off int, len int) : int from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Attribute Modifier final in attribute private client : AmazonS3Client from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Attribute Modifier final in attribute private bucket : String from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Remove Parameter pos : long in method private reopen(pos long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
>   Add Parameter targetPos : long in method private lazySeek(targetPos long, len long) : void from class org.apache.hadoop.fs.s3a.S3AInputStream
