### ISSUE TITLE
Checkout conflict with files

### ISSUE THREAD

**Issue by Symbolk** [tsantalis/RefactoringMiner#43]
Hi, I clone the refactoring-toy-example and run RefactoringMiner on it with the option: "-a D:\repos\refactoring-toy-example", but it fails when checkout some commits, let alone correctly mining refactorings.

Here are part of the error msg:

```sh
1 refactorings found in commit d4bce13a443cf12da40a77c16c1e591f4f985b47
1 refactorings found in commit 9a5c33b16d07d62651ea80552e8782974c96bb8a
No refactorings found in commit a5a7f852e45c7cadc8d1524bd4d14a1e39785aa5
1 refactorings found in commit 0bb0526b70870d57cbac9fcc8c4a7346a4ce5879
Error processing commit f3b628f8f9c71a2cdfa052025c4a1ed78ee4c45d
org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/reptile/Snake.java
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:279)
	at org.refactoringminer.util.GitServiceImpl.checkout(GitServiceImpl.java:120)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:134)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:101)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:284)
	at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:63)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/reptile/Snake.java
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:516)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:275)
	... 6 more
Error processing commit 1328d7873efe6caaffaf635424e19a4bb5e786a8
org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/felines/Animal.java
src/org/felines/AnimalSuper.java
src/org/reptile/Snake.java
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:279)
	at org.refactoringminer.util.GitServiceImpl.checkout(GitServiceImpl.java:120)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:134)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:101)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:284)
	at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:63)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/felines/Animal.java
src/org/felines/AnimalSuper.java
src/org/reptile/Snake.java
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:516)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:275)
	... 6 more
Error processing commit 0a46ed5c56c8b1576dfc92f3ec5bc2f0ea68aafe
org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/felines/Animal.java
src/org/felines/AnimalSuper.java
src/org/reptile/AnimalMarilho.java
src/org/reptile/Reptile.java
src/org/reptile/Snake.java
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:279)
	at org.refactoringminer.util.GitServiceImpl.checkout(GitServiceImpl.java:120)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:134)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:101)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:284)
	at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:63)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
src/org/felines/Animal.java
src/org/felines/AnimalSuper.java
src/org/reptile/AnimalMarilho.java
src/org/reptile/Reptile.java
src/org/reptile/Snake.java
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:516)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:275)
	... 6 more
```

**Comment by tsantalis** [comment]
@Symbolk I am unable to reproduce this problem. Probably, your locally cloned repository is corrupted. Try to delete it and clone it again. This is the output I just got:

```
2018-11-16 23:07:09 INFO  Cloning https://github.com/danilofes/refactoring-toy-example.git ...
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example 9a5c33b16d07d62651ea80552e8782974c96bb8a ...
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example d4bce13a443cf12da40a77c16c1e591f4f985b47 ...
Refactorings at d4bce13a443cf12da40a77c16c1e591f4f985b47
Move Method	public barkBark(manager DogManager) : void from class org.animals.Dog to public barkBark(dog Dog) : void from class org.DogManager
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example a5a7f852e45c7cadc8d1524bd4d14a1e39785aa5 ...
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example 9a5c33b16d07d62651ea80552e8782974c96bb8a ...
Refactorings at 9a5c33b16d07d62651ea80552e8782974c96bb8a
Move Attribute	public magicNumber : int from class org.DogManager to class org.animals.Dog
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example 0bb0526b70870d57cbac9fcc8c4a7346a4ce5879 ...
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example a5a7f852e45c7cadc8d1524bd4d14a1e39785aa5 ...
Refactorings at a5a7f852e45c7cadc8d1524bd4d14a1e39785aa5
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example c286db365e7374fe4d08f54077abb7fba81dd296 ...
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example 0bb0526b70870d57cbac9fcc8c4a7346a4ce5879 ...
Refactorings at 0bb0526b70870d57cbac9fcc8c4a7346a4ce5879
Rename Method	public bark() : void renamed to public barkBark() : void in class org.animals.Dog
2018-11-16 23:07:11 INFO  Checking out tmp\refactoring-toy-example 1328d7873efe6caaffaf635424e19a4bb5e786a8 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example f3b628f8f9c71a2cdfa052025c4a1ed78ee4c45d ...
Refactorings at f3b628f8f9c71a2cdfa052025c4a1ed78ee4c45d
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 0a46ed5c56c8b1576dfc92f3ec5bc2f0ea68aafe ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 1328d7873efe6caaffaf635424e19a4bb5e786a8 ...
Refactorings at 1328d7873efe6caaffaf635424e19a4bb5e786a8
Extract Interface	org.felines.AnimalSuper from classes [org.felines.Animal]
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 638f37ca6b4dcdbb6a4735f93e37445aeef79749 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 0a46ed5c56c8b1576dfc92f3ec5bc2f0ea68aafe ...
Refactorings at 0a46ed5c56c8b1576dfc92f3ec5bc2f0ea68aafe
Push Down Attribute	protected age : int from class org.reptile.AnimalMarilho to class org.reptile.Reptile
Push Down Attribute	protected name : int from class org.reptile.AnimalMarilho to class org.reptile.Reptile
Push Down Method	public getName() : int from class org.reptile.AnimalMarilho to public getName() : int from class org.reptile.Reptile
Push Down Method	public setName(name int) : void from class org.reptile.AnimalMarilho to public setName(name int) : void from class org.reptile.Reptile
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 0e193b7d02902c6f2abf7c88eebe937d1ac5fc51 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 638f37ca6b4dcdbb6a4735f93e37445aeef79749 ...
Refactorings at 638f37ca6b4dcdbb6a4735f93e37445aeef79749
Push Down Method	public equals(obj Object) : boolean from class org.reptile.Reptile to public equals(obj Object) : boolean from class org.reptile.TurtleMarinha
Push Down Method	public equals(obj Object) : boolean from class org.reptile.Reptile to public equals(obj Object) : boolean from class org.reptile.TurtleTerrarium
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example b61e75b773f48e680f5bb7362445ba0642c2ee91 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 0e193b7d02902c6f2abf7c88eebe937d1ac5fc51 ...
Refactorings at 0e193b7d02902c6f2abf7c88eebe937d1ac5fc51
Push Down Method	public hashCode() : int from class org.reptile.AnimalMarilho to public hashCode() : int from class org.reptile.Reptile
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 6bbfab9e7051362aad9d993f5f6a013b73e75117 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example b61e75b773f48e680f5bb7362445ba0642c2ee91 ...
Refactorings at b61e75b773f48e680f5bb7362445ba0642c2ee91
Push Down Method	public equals(obj Object) : boolean from class org.reptile.AnimalMarilho to public equals(obj Object) : boolean from class org.reptile.Reptile
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example bbd8dc082406a950adf73b7211c887bfab6480f1 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 6bbfab9e7051362aad9d993f5f6a013b73e75117 ...
Refactorings at 6bbfab9e7051362aad9d993f5f6a013b73e75117
Pull Up Attribute	protected age : int from class org.reptile.Reptile to class org.reptile.AnimalMarilho
Pull Up Attribute	protected name : int from class org.reptile.Reptile to class org.reptile.AnimalMarilho
Pull Up Attribute	protected spead : int from class org.reptile.Reptile to class org.reptile.AnimalMarilho
Pull Up Attribute	protected action : String from class org.reptile.Reptile to class org.reptile.AnimalMarilho
Pull Up Method	public getName() : int from class org.reptile.Reptile to public getName() : int from class org.reptile.AnimalMarilho
Pull Up Method	public setName(name int) : void from class org.reptile.Reptile to public setName(name int) : void from class org.reptile.AnimalMarilho
Pull Up Method	public getSpead() : int from class org.reptile.Reptile to public getSpead() : int from class org.reptile.AnimalMarilho
Pull Up Method	public setSpead(spead int) : void from class org.reptile.Reptile to public setSpead(spead int) : void from class org.reptile.AnimalMarilho
Pull Up Method	public getAction() : String from class org.reptile.Reptile to public getAction() : String from class org.reptile.AnimalMarilho
Pull Up Method	public setAction(action String) : void from class org.reptile.Reptile to public setAction(action String) : void from class org.reptile.AnimalMarilho
Pull Up Method	public hashCode() : int from class org.reptile.Reptile to public hashCode() : int from class org.reptile.AnimalMarilho
Pull Up Method	public equals(obj Object) : boolean from class org.reptile.Reptile to public equals(obj Object) : boolean from class org.reptile.AnimalMarilho
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 9803046111744317efaa65a83e65ce8ceb0c15c2 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example bbd8dc082406a950adf73b7211c887bfab6480f1 ...
Refactorings at bbd8dc082406a950adf73b7211c887bfab6480f1
Extract Superclass	org.reptile.AnimalMarilho from classes [org.reptile.Reptile]
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 9b23cc2184438f93923c972c45b7caeb43d77d24 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 9803046111744317efaa65a83e65ce8ceb0c15c2 ...
Refactorings at 9803046111744317efaa65a83e65ce8ceb0c15c2
Push Down Method	public getAge() : int from class org.reptile.Reptile to public getAge() : int from class org.reptile.TurtleMarinha
Push Down Method	public getAge() : int from class org.reptile.Reptile to public getAge() : int from class org.reptile.TurtleTerrarium
Push Down Method	public setAge(age int) : void from class org.reptile.Reptile to public setAge(age int) : void from class org.reptile.TurtleMarinha
Push Down Method	public setAge(age int) : void from class org.reptile.Reptile to public setAge(age int) : void from class org.reptile.TurtleTerrarium
Refactorings at 9b23cc2184438f93923c972c45b7caeb43d77d24
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 802e21bffe95f0740f44d1a45e3c22adae0ba48c ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example a1b3a91d1a423f2b7360e009e47f30aedb663b6f ...
Refactorings at a1b3a91d1a423f2b7360e009e47f30aedb663b6f
Rename Class	org.reptile.Turtle renamed to org.reptile.TurtleMarinha
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 5849e143567474f037950f005d994729de0775fc ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 802e21bffe95f0740f44d1a45e3c22adae0ba48c ...
Refactorings at 802e21bffe95f0740f44d1a45e3c22adae0ba48c
Extract Superclass	org.reptile.Reptile from classes [org.reptile.Turtle]
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 3f3552830d3e464f96f99bd55641a7c7b16bdd11 ...
2018-11-16 23:07:12 INFO  Checking out tmp\refactoring-toy-example 5849e143567474f037950f005d994729de0775fc ...
Refactorings at 5849e143567474f037950f005d994729de0775fc
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example f35b2c8eb8c320f173237e44d04eefb4634649a2 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 3f3552830d3e464f96f99bd55641a7c7b16bdd11 ...
Refactorings at 3f3552830d3e464f96f99bd55641a7c7b16bdd11
Push Down Attribute	private speed : int from class org.felines.Feline to class org.felines.Tiger
Push Down Method	public getSpeed() : int from class org.felines.Feline to public getSpeed() : int from class org.felines.Tiger
Push Down Method	public setSpeed(speed int) : void from class org.felines.Feline to public setSpeed(speed int) : void from class org.felines.Tiger
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example c0a051fdeb02fd4374ebe625d6af9e3125a2b9af ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example f35b2c8eb8c320f173237e44d04eefb4634649a2 ...
Refactorings at f35b2c8eb8c320f173237e44d04eefb4634649a2
Extract Method	private sleepNight() : void extracted from public sleep() : void in class org.felines.Cat
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 7ebd3deba1ae42ff1e9c8585fc304839c5288863 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example c0a051fdeb02fd4374ebe625d6af9e3125a2b9af ...
Refactorings at c0a051fdeb02fd4374ebe625d6af9e3125a2b9af
Pull Up Attribute	private speed : int from class org.felines.Tiger to class org.felines.Feline
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 217e55ff9d01038a23508d24fe4b8af33ac449d1 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 7ebd3deba1ae42ff1e9c8585fc304839c5288863 ...
Refactorings at 7ebd3deba1ae42ff1e9c8585fc304839c5288863
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 32bf625304762aaad475fa817150634038f07af5 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 217e55ff9d01038a23508d24fe4b8af33ac449d1 ...
Refactorings at 217e55ff9d01038a23508d24fe4b8af33ac449d1
Refactorings at 32bf625304762aaad475fa817150634038f07af5
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 9a9878aeb62a6bb6ff2bed6c03dd1dd7ed1f202b ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 92b201345f730110445d83f4fefe8ae88bc4872b ...
Refactorings at 92b201345f730110445d83f4fefe8ae88bc4872b
Pull Up Attribute	private age : int from class org.felines.Tiger to class org.felines.Feline
Pull Up Attribute	private name : int from class org.felines.Tiger to class org.felines.Feline
Pull Up Method	public getAge() : int from class org.felines.Tiger to public getAge() : int from class org.felines.Feline
Pull Up Method	public setAge(age int) : void from class org.felines.Tiger to public setAge(age int) : void from class org.felines.Feline
Pull Up Method	public getName() : int from class org.felines.Tiger to public getName() : int from class org.felines.Feline
Pull Up Method	public setName(name int) : void from class org.felines.Tiger to public setName(name int) : void from class org.felines.Feline
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example c946700398fc43a437d124f027a9bd3ba25bcafc ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 9a9878aeb62a6bb6ff2bed6c03dd1dd7ed1f202b ...
Refactorings at 9a9878aeb62a6bb6ff2bed6c03dd1dd7ed1f202b
Pull Up Method	public meow() : void from class org.felines.Cat to public meow() : void from class org.felines.Feline
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 16be1426aeb34352ba5d97811f3a721b11e3ae00 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example c946700398fc43a437d124f027a9bd3ba25bcafc ...
Refactorings at c946700398fc43a437d124f027a9bd3ba25bcafc
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 0c5c24356f3179ee320c3318f91278520caafb3a ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 16be1426aeb34352ba5d97811f3a721b11e3ae00 ...
Refactorings at 16be1426aeb34352ba5d97811f3a721b11e3ae00
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 12b11bf39cb4800e3fa57fb1112c5fbda26de3df ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 0c5c24356f3179ee320c3318f91278520caafb3a ...
Refactorings at 0c5c24356f3179ee320c3318f91278520caafb3a
Move Class	org.felines.Feline moved to org.birds.Feline
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example b2c7be7001d4833d14d7fee8c7c989279b4ad039 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 12b11bf39cb4800e3fa57fb1112c5fbda26de3df ...
Refactorings at 12b11bf39cb4800e3fa57fb1112c5fbda26de3df
Move Class	org.animals.Tiger moved to org.felines.Tiger
Refactorings at b2c7be7001d4833d14d7fee8c7c989279b4ad039
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 70b71b7fd3c5973511904c468e464d4910597928 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 05c1e773878bbacae64112f70964f4f2f7944398 ...
Refactorings at 05c1e773878bbacae64112f70964f4f2f7944398
Extract Superclass	org.felines.Feline from classes [org.felines.Cat]
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 70b71b7fd3c5973511904c468e464d4910597928 ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 60226924fead7d0c4646df4f4fd65667e83da6dc ...
Refactorings at 60226924fead7d0c4646df4f4fd65667e83da6dc
Move Class	org.animals.Bird moved to org.birds.Bird
Move Class	org.animals.Chicken moved to org.birds.Chicken
Move Class	org.animals.Duck moved to org.birds.Duck
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example e78b02fe027621aec1227cbf5555c75775ba296b ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 70b71b7fd3c5973511904c468e464d4910597928 ...
Refactorings at 70b71b7fd3c5973511904c468e464d4910597928
Move Class	org.animals.Cat moved to org.felines.Cat
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 40950c317bd52ea5ce4cf0d19707fe426b66649c ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 63cbed99a601e79c6a0ae389b2a57acdbd3e1b44 ...
Refactorings at 63cbed99a601e79c6a0ae389b2a57acdbd3e1b44
Rename Class	org.animals.Cow renamed to org.animals.CowRenamed
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 36287f7c3b09eff78395267a3ac0d7da067863fd ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 58495630295833c9d73559bd958c2f95339f9c62 ...
Refactorings at 58495630295833c9d73559bd958c2f95339f9c62
Extract Superclass	org.animals.Bird from classes [org.animals.Chicken, org.animals.Duck]
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 36287f7c3b09eff78395267a3ac0d7da067863fd ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 40950c317bd52ea5ce4cf0d19707fe426b66649c ...
Refactorings at 40950c317bd52ea5ce4cf0d19707fe426b66649c
Extract Method	public takeABreath() : void extracted from public bark() : void in class org.animals.Dog
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example cd61fd2a70828030ccb3cf46d8719f8b204c52ed ...
2018-11-16 23:07:13 INFO  Checking out tmp\refactoring-toy-example 36287f7c3b09eff78395267a3ac0d7da067863fd ...
Refactorings at 36287f7c3b09eff78395267a3ac0d7da067863fd
Pull Up Attribute	private age : int from class org.animals.Labrador to class org.animals.Dog
Pull Up Attribute	private age : int from class org.animals.Poodle to class org.animals.Dog
Pull Up Method	public getAge() : int from class org.animals.Labrador to public getAge() : int from class org.animals.Dog
Pull Up Method	public getAge() : int from class org.animals.Poodle to public getAge() : int from class org.animals.Dog
Refactorings at cd61fd2a70828030ccb3cf46d8719f8b204c52ed
2018-11-16 23:07:13 INFO  Analyzed refactoring-toy-example [Commits: 38, Errors: 0, Refactorings: 57]
```
