### ISSUE TITLE
String index out of range -56

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#49]
`Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -56
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:117)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at c_main.Extract_Refact.main(Extract_Refact.java:22)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -56
	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.argumentsWithIdenticalMethodCalls(UMLOperationBodyMapper.java:2014)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1268)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1055)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.initialize(UMLOperationBodyMapper.java:131)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMappings(UMLOperationBodyMapper.java:426)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMethodInvocationRenameReplacements(UMLOperationBodyMapper.java:900)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.findConsistentMethodInvocationRenames(UMLClassBaseDiff.java:647)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:562)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:88)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:145)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:156)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	... 2 more
`

**Comment by tsantalis** [comment]
Please provide the commit URL to replicate the bug.

**Comment by mashalahmad** [comment]
[link](https://github.com/apache/xerces2-j)

**Comment by tsantalis** [comment]
I need the SHA-1 of the commit too.

**Comment by mashalahmad** [comment]
2019-02-21 12:32:20 WARN  Ignored revision 256a43d2ab369ca3d42c1581694c8ccd6dfacf52 due to error

**Comment by tsantalis** [comment]
Duplicated of issue #50 
Fixed in commit https://github.com/tsantalis/RefactoringMiner/commit/9bf409e336bbda7141478a148d1f8a06f2467a6d
