### ISSUE TITLE
String index out of range: -18

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#50]
Got another error for 

> https://github.com/Atmosphere/atmosphere

`2019-02-20 15:50:17 INFO  Processing tmp\atmosphere c73ead88bb7dd7730bb4e425201835793dc3762d ...
2019-02-20 15:50:17 WARN  Ignored revision c73ead88bb7dd7730bb4e425201835793dc3762d due to error
java.lang.StringIndexOutOfBoundsException: String index out of range: -18
	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.argumentsWithIdenticalMethodCalls(UMLOperationBodyMapper.java:2014)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1268)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1055)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.initialize(UMLOperationBodyMapper.java:131)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMappings(UMLOperationBodyMapper.java:426)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMethodInvocationRenameReplacements(UMLOperationBodyMapper.java:900)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.findConsistentMethodInvocationRenames(UMLClassBaseDiff.java:647)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:562)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:88)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:145)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:156)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at c_main.Extract_Refact.main(Extract_Refact.java:27)
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -18
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:117)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at c_main.Extract_Refact.main(Extract_Refact.java:27)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -18
	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.argumentsWithIdenticalMethodCalls(UMLOperationBodyMapper.java:2014)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1268)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1055)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.initialize(UMLOperationBodyMapper.java:131)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMappings(UMLOperationBodyMapper.java:426)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getMethodInvocationRenameReplacements(UMLOperationBodyMapper.java:900)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.findConsistentMethodInvocationRenames(UMLClassBaseDiff.java:647)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:562)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:88)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:145)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:156)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	... 2 more
`

**Comment by mashalahmad** [comment]
another error at this link [this](https://github.com/clojure/clojure)
`2019-02-20 16:09:15 INFO  Processing tmp\clojure 97c187fbae66df23d6716538b64ba46d67847792 ...
2019-02-20 16:09:15 WARN  Ignored revision 97c187fbae66df23d6716538b64ba46d67847792 due to error
java.lang.StringIndexOutOfBoundsException: String index out of range: 27
	at java.lang.String.charAt(String.java:658)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.isInsideSingleQuotes(UMLOperationBodyMapper.java:2194)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.replaceVariablesWithArguments(UMLOperationBodyMapper.java:2175)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1244)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1055)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:233)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.createMapperForExtractedMethod(ExtractOperationDetection.java:116)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.check(ExtractOperationDetection.java:39)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForExtractedOperations(UMLClassBaseDiff.java:1064)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:90)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:145)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:156)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at c_main.Extract_Refact.main(Extract_Refact.java:27)
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 27
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:117)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at c_main.Extract_Refact.main(Extract_Refact.java:27)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 27
	at java.lang.String.charAt(String.java:658)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.isInsideSingleQuotes(UMLOperationBodyMapper.java:2194)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.replaceVariablesWithArguments(UMLOperationBodyMapper.java:2175)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1244)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1055)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:233)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.createMapperForExtractedMethod(ExtractOperationDetection.java:116)
	at gr.uom.java.xmi.diff.ExtractOperationDetection.check(ExtractOperationDetection.java:39)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForExtractedOperations(UMLClassBaseDiff.java:1064)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:90)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:145)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:156)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	... 2 more
`
