### ISSUE TITLE
StringIndexOutOfBoundsException when detecting refactorings between two commits

### ISSUE THREAD

**Issue by jzheng2017** [tsantalis/RefactoringMiner#527]
**Problem**
When detecting refactoring operations with the `detectBetweenCommits` it throws a StringIndexOutOfBoundsException

**Commit**
Between [7643b12421100d29fd2b78053e77bcb04a251b2e](https://github.com/apache/commons-text/commit/7643b12421100d29fd2b78053e77bcb04a251b2e) and [f451f15143019052aff15758146cbf4288ad3a11](https://github.com/apache/commons-text/commit/f451f15143019052aff15758146cbf4288ad3a11). And seems to fail specifically on [3c4d37d68a18aa5c93b95f27645c7589c58e54e8](https://github.com/apache/commons-text/commit/3c4d37d68a18aa5c93b95f27645c7589c58e54e8)

**Stacktrace**
```
[main] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision 3c4d37d68a18aa5c93b95f27645c7589c58e54e8 due to error
java.lang.StringIndexOutOfBoundsException: String index out of range: 26
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1517)
	at gr.uom.java.xmi.LeafType.simpleNameOf(LeafType.java:27)
	at gr.uom.java.xmi.LeafType.<init>(LeafType.java:13)
	at gr.uom.java.xmi.UMLType.extractTypeObject(UMLType.java:216)
	at gr.uom.java.xmi.decomposition.OperationInvocation.matchesOperation(OperationInvocation.java:299)
	at gr.uom.java.xmi.decomposition.VariableReferenceExtractor.findReferences(VariableReferenceExtractor.java:29)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.findMatchingVariablesWithoutVariableDeclarationMapping(VariableReplacementAnalysis.java:365)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.<init>(VariableReplacementAnalysis.java:157)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.computeRefactoringsWithinBody(UMLOperationBodyMapper.java:2147)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getRefactorings(UMLOperationBodyMapper.java:2097)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.processMapperRefactorings(UMLAbstractClassDiff.java:782)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:625)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1992)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:159)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:115)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:750)
	at nl.jiankai.refactoring.core.refactoring.refactoringminer.RefactoringMinerRefactoringDetector.detectRefactoringBetweenCommit(RefactoringMinerRefactoringDetector.java:30)
	at nl.jiankai.refactoring.Main.findAllRefactoredMethods(Main.java:171)
	at nl.jiankai.refactoring.Main.lambda$main$1(Main.java:84)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at nl.jiankai.refactoring.Main.main(Main.java:83)
```
**Context**
It seems to fail at the `map == null ? Collections` part where it tries to access index 26 where the length is 26, so it goes out of bounds.

**Comment by tsantalis** [comment]
@jzheng2017 
Thank you for reporting this exception.
The issue has been fixed in commit aa84915e14cbb8e21e03098ed76e42dc42cde1db
