### ISSUE TITLE
NullPointerException on String

### ISSUE THREAD

**Issue by jzheng2017** [tsantalis/RefactoringMiner#528]
**Problem**
When detecting refactoring operations with the `detectBetweenCommits` it throws a NullPointerException

**Commit**
It seems to fail specifically on [8150e37cc3318ed53241563d051f169d6081fbd5](https://github.com/apache/httpcomponents-client/commit/8150e37cc3318ed53241563d051f169d6081fbd5)

**Stacktrace**
```
[ForkJoinPool.commonPool-worker-2] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision 8150e37cc3318ed53241563d051f169d6081fbd5 due to error
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "completeString2" is null
	at gr.uom.java.xmi.decomposition.ReplacementUtil.performReplacement(ReplacementUtil.java:103)
	at gr.uom.java.xmi.decomposition.StringBasedHeuristics.identicalAfterVariableAndTypeReplacements(StringBasedHeuristics.java:1728)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:7815)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:7645)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:6143)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:3646)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:317)
	at gr.uom.java.xmi.diff.UMLClassDiff.createBodyMappers(UMLClassDiff.java:152)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:97)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:115)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectBetweenCommits(GitHistoryRefactoringMinerImpl.java:750)
	at nl.jiankai.refactoring.core.refactoring.refactoringminer.RefactoringMinerRefactoringDetector.detectRefactoringBetweenCommit(RefactoringMinerRefactoringDetector.java:30)
	at nl.jiankai.refactoring.Main.findAllRefactoredMethods(Main.java:207)
	at nl.jiankai.refactoring.Main.lambda$main$2(Main.java:88)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at nl.jiankai.refactoring.Main.lambda$main$3(Main.java:87)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:679)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by tsantalis** [comment]
Thank you @jzheng2017 for reporting this issue.
It has been fixed in commit 7d6173394e815f567ced76fe0fa170c910e485e7
