### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by likeanowl** [tsantalis/RefactoringMiner#53]
Project: https://github.com/JetBrains/intellij-community
last found refactorings at a14bec7a108a0da9a24541bd134a1b7d682770e8
version of RMiner: release 1.0.0

Full exception trace: 
```
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: 99
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:102)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:245)
	at com.company.Main.main(Main.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 99
	at java.lang.String.substring(String.java:1963)
	at gr.uom.java.xmi.diff.MovedClassToAnotherSourceFolder.getRenamePattern(MovedClassToAnotherSourceFolder.java:16)
	at gr.uom.java.xmi.diff.UMLModelDiff.getMoveClassRefactorings(UMLModelDiff.java:669)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:720)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97)
	... 2 more
```

**Comment by tsantalis** [comment]
@likeanowl This issue has been fixed. Please build RefactoringMiner from the latest commit.

**Comment by likeanowl** [comment]
@tsantalis Thank you for quick response!
On a fresh build from master a new exception occurred on same repository. I created a new issue for this case: #54
