### ISSUE TITLE
NullPointerException when detecting at specific commit

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#537]
- [x] I get a NPE when assessing https://github.com/zalando/nakadi/commit/11030f39a59542c5b4a82e37fa28f000a46a84a3 

```
java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.UMLType.equals(Object)" because the return value of "gr.uom.java.xmi.decomposition.VariableDeclaration.getType()" is null
        at gr.uom.java.xmi.diff.UMLClassBaseDiff.mappedElementsMoreThanNonMappedT1AndT2(UMLClassBaseDiff.java:1867)
        at gr.uom.java.xmi.diff.UMLClassBaseDiff.updateMapperSet(UMLClassBaseDiff.java:1506)
        at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:1033)
        at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:111)
        at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:161)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:118)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:571)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:43)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:44)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:25)
```

- [x] Similarly, I get a NPE when assessing https://github.com/apache/cassandra/commit/1adbea5a068287f42f2421e558f4c404c69aea74 

```
java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.OperationBody.getCompositeStatement()" because the return value of "gr.uom.java.xmi.VariableDeclarationContainer.
getBody()" is null
        at gr.uom.java.xmi.decomposition.StringBasedHeuristics.commonConditional(StringBasedHeuristics.java:2806)
        at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8259)
        at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4689)
        at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:955)
        at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
        at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
        at gr.uom.java.xmi.diff.UMLClassDiff.processAttributes(UMLClassDiff.java:51)
        at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:112)
        at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:161)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:118)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:571)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:43)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:44)
        at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:25)
```

**Comment by tsantalis** [comment]
@victorgveloso 
Both problems fixed.
