### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by likeanowl** [tsantalis/RefactoringMiner#54]
RMiner version: fresh build from master (07.04.2019)
Repository: [intellij-community](https://github.com/JetBrains/intellij-community)
Commit hash: 6b0d61e417a15ccad075fa80837c7f13173d0fea (https://github.com/JetBrains/intellij-community/commit/6b0d61e417a15ccad075fa80837c7f13173d0fea)

Full stacktrace:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:117)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:337)
	at com.company.Main.main(Main.java:34)
Caused by: java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:231)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:129)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:54)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.createModel(GitHistoryRefactoringMinerImpl.java:360)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:151)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:112)
	... 2 more
```

**Comment by likeanowl** [comment]
I guess this may occur because commit contain Kotlin file, and, as I know, RMiner supports only Java files. 
Is there a way to configure RMiner  to ignore other languages than Java?

**Comment by tsantalis** [comment]
I am not able to replicate the exception. It seems you didn't build properly the project.
The exception is in line 54 of UMLModelASTReader `this.parser = ASTParser.newParser(AST.JLS11);`
I suggest to build from scratch, because it seems you don't have the latest Eclipse JDT libraries.
Also, remove any existing jar files from the local lib folder. All project dependencies are now downloaded from maven using the gradle wrapper.
