### ISSUE TITLE
StackOverflow hapifhir/hapi-fhir faf7c410e1

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#578]
StackOverflow thrown while analyzing https://github.com/hapifhir/hapi-fhir/commit/faf7c410e16073bce794396c620b127dd5c92db2
```
80028081 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit faf7c410e16073bce794396c620b127dd5c92db2
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.StackOverflowError: null
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3955)
	at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4290)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3955)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
	at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Matcher.match(Matcher.java:1755)
	at java.base/java.util.regex.Matcher.matches(Matcher.java:712)
	at gr.uom.java.xmi.decomposition.StringBasedHeuristics.containsMethodSignatureOfAnonymousClass(StringBasedHeuristics.java:66)
	at gr.uom.java.xmi.decomposition.ReplacementUtil.performReplacement(ReplacementUtil.java:123)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacements(UMLOperationBodyMapper.java:11239)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:7804)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:970)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:123)
	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:46)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:751)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10880)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
```

**Comment by tsantalis** [comment]
@victorgveloso 
**FIXED**

Refactorings at faf7c410e16073bce794396c620b127dd5c92db2
Rename Class	ca.uhn.fhir.model.valueset.BundleEntryTransactionOperationEnum renamed to ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Variable Type	entryTransactionOperation : BundleEntryTransactionOperationEnum to entryTransactionOperation : BundleEntryTransactionMethodEnum in method public addResource(theResource IResource, theContext FhirContext, theServerBase String) : BundleEntry from class ca.uhn.fhir.model.api.Bundle
Rename Method	public getTransactionOperation() : BoundCodeDt<BundleEntryTransactionOperationEnum> renamed to public getTransactionMethod() : BoundCodeDt<BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.api.BundleEntry
Rename Method	public setTransactionOperation(theTransactionOperation BoundCodeDt<BundleEntryTransactionOperationEnum>) : void renamed to public setTransactionMethod(theTransactionOperation BoundCodeDt<BundleEntryTransactionMethodEnum>) : void in class ca.uhn.fhir.model.api.BundleEntry
Change Attribute Type	myTransactionOperation : BoundCodeDt<BundleEntryTransactionOperationEnum> to myTransactionOperation : BoundCodeDt<BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.api.BundleEntry
Change Return Type	BoundCodeDt<BundleEntryTransactionOperationEnum> to BoundCodeDt<BundleEntryTransactionMethodEnum> in method public getTransactionMethod() : BoundCodeDt<BundleEntryTransactionMethodEnum> from class ca.uhn.fhir.model.api.BundleEntry
Change Parameter Type	theTransactionOperation : BoundCodeDt<BundleEntryTransactionOperationEnum> to theTransactionOperation : BoundCodeDt<BundleEntryTransactionMethodEnum> in method public setTransactionMethod(theTransactionOperation BoundCodeDt<BundleEntryTransactionMethodEnum>) : void from class ca.uhn.fhir.model.api.BundleEntry
Change Variable Type	nextResouceOperationIn : BundleEntryTransactionOperationEnum to nextResouceOperationIn : BundleEntryTransactionMethodEnum in method public transaction(theResources List<IResource>) : List<IResource> from class ca.uhn.fhir.jpa.dao.FhirSystemDaoDstu1
Change Variable Type	nextResouceOperationOut : BundleEntryTransactionOperationEnum to nextResouceOperationOut : BundleEntryTransactionMethodEnum in method public transaction(theResources List<IResource>) : List<IResource> from class ca.uhn.fhir.jpa.dao.FhirSystemDaoDstu1
Change Attribute Type	CODE_TO_ENUM : Map<String,BundleEntryTransactionOperationEnum> to CODE_TO_ENUM : Map<String,BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Attribute Type	SYSTEM_TO_CODE_TO_ENUM : Map<String,Map<String,BundleEntryTransactionOperationEnum>> to SYSTEM_TO_CODE_TO_ENUM : Map<String,Map<String,BundleEntryTransactionMethodEnum>> in class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Attribute Type	VALUESET_BINDER : IValueSetEnumBinder<BundleEntryTransactionOperationEnum> to VALUESET_BINDER : IValueSetEnumBinder<BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Parameter Type	theEnum : BundleEntryTransactionOperationEnum to theEnum : BundleEntryTransactionMethodEnum in method public toCodeString(theEnum BundleEntryTransactionMethodEnum) : String from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum.VALUESET_BINDER.new IValueSetEnumBinder<BundleEntryTransactionMethodEnum>
Change Parameter Type	theEnum : BundleEntryTransactionOperationEnum to theEnum : BundleEntryTransactionMethodEnum in method public toSystemString(theEnum BundleEntryTransactionMethodEnum) : String from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum.VALUESET_BINDER.new IValueSetEnumBinder<BundleEntryTransactionMethodEnum>
Change Return Type	BundleEntryTransactionOperationEnum to BundleEntryTransactionMethodEnum in method public fromCodeString(theCodeString String) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum.VALUESET_BINDER.new IValueSetEnumBinder<BundleEntryTransactionMethodEnum>
Change Variable Type	map : Map<String,BundleEntryTransactionOperationEnum> to map : Map<String,BundleEntryTransactionMethodEnum> in method public fromCodeString(theCodeString String, theSystemString String) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum.VALUESET_BINDER.new IValueSetEnumBinder<BundleEntryTransactionMethodEnum>
Change Return Type	BundleEntryTransactionOperationEnum to BundleEntryTransactionMethodEnum in method public fromCodeString(theCodeString String, theSystemString String) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum.VALUESET_BINDER.new IValueSetEnumBinder<BundleEntryTransactionMethodEnum>
Change Variable Type	next : BundleEntryTransactionOperationEnum to next : BundleEntryTransactionMethodEnum in initializer BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Variable Type	retVal : BundleEntryTransactionOperationEnum to retVal : BundleEntryTransactionMethodEnum in method public forCode(theCode String) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Change Return Type	BundleEntryTransactionOperationEnum to BundleEntryTransactionMethodEnum in method public forCode(theCode String) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.valueset.BundleEntryTransactionMethodEnum
Rename Attribute	ENTRY_TRANSACTION_OPERATION : ResourceMetadataKeyEnum<BundleEntryTransactionOperationEnum> to ENTRY_TRANSACTION_METHOD : ResourceMetadataKeyEnum<BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.api.ResourceMetadataKeyEnum
Change Attribute Type	ENTRY_TRANSACTION_OPERATION : ResourceMetadataKeyEnum<BundleEntryTransactionOperationEnum> to ENTRY_TRANSACTION_METHOD : ResourceMetadataKeyEnum<BundleEntryTransactionMethodEnum> in class ca.uhn.fhir.model.api.ResourceMetadataKeyEnum
Change Return Type	BundleEntryTransactionOperationEnum to BundleEntryTransactionMethodEnum in method public get(theResource IResource) : BundleEntryTransactionMethodEnum from class ca.uhn.fhir.model.api.ResourceMetadataKeyEnum.ENTRY_TRANSACTION_METHOD.new ResourceMetadataKeyEnum<BundleEntryTransactionMethodEnum>
Change Parameter Type	theObject : BundleEntryTransactionOperationEnum to theObject : BundleEntryTransactionMethodEnum in method public put(theResource IResource, theObject BundleEntryTransactionMethodEnum) : void from class ca.uhn.fhir.model.api.ResourceMetadataKeyEnum.ENTRY_TRANSACTION_METHOD.new ResourceMetadataKeyEnum<BundleEntryTransactionMethodEnum>
