### ISSUE TITLE
OutOfMemoryError TIBCOSoftware/jasperreports 5aead10c

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#580]
Exception thrown while analyzing 
 https://github.com/TIBCOSoftware/jasperreports/commit/5aead10c83b58029d41d3169400b988b935d1992
```
86567580 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 5aead10c83b58029d41d3169400b988b935d1992
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:769)
	at java.base/java.lang.StringBuffer.toString(StringBuffer.java:716)
	at org.eclipse.jdt.internal.core.dom.NaiveASTFlattener.getResult(NaiveASTFlattener.java:125)
	at gr.uom.java.xmi.decomposition.Visitor.stringify(Visitor.java:935)
	at gr.uom.java.xmi.decomposition.OperationInvocation.<init>(OperationInvocation.java:92)
	at gr.uom.java.xmi.decomposition.Visitor.visit(Visitor.java:518)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:220)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:223)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:181)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:183)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at gr.uom.java.xmi.decomposition.AbstractExpression.<init>(AbstractExpression.java:48)
	at gr.uom.java.xmi.decomposition.TernaryOperatorExpression.<init>(TernaryOperatorExpression.java:21)
	at gr.uom.java.xmi.decomposition.Visitor.visit(Visitor.java:133)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:178)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:183)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at gr.uom.java.xmi.decomposition.AbstractExpression.<init>(AbstractExpression.java:48)
	at gr.uom.java.xmi.decomposition.TernaryOperatorExpression.<init>(TernaryOperatorExpression.java:21)
	at gr.uom.java.xmi.decomposition.Visitor.visit(Visitor.java:133)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:178)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.ConditionalExpression.accept0(ConditionalExpression.java:183)
```

**Comment by tsantalis** [comment]
@victorgveloso 
**FIXED**

Refactorings at 5aead10c83b58029d41d3169400b988b935d1992
Rename Class	net.sf.jasperreports.chartthemes.simple.handlers.BackgoundImageAlignmentFieldHandler renamed to net.sf.jasperreports.chartthemes.simple.handlers.ImageAlignmentFieldHandler
Rename Method	public getChartBorderPaint() : PaintProvider renamed to public getBorderPaint() : PaintProvider in class net.sf.jasperreports.chartthemes.simple.ChartSettings
Rename Method	public setChartBorderPaint(chartBorderPaint PaintProvider) : void renamed to public setBorderPaint(borderPaint PaintProvider) : void in class net.sf.jasperreports.chartthemes.simple.ChartSettings
Rename Attribute	PROPERTY_chartBorderPaint : String to PROPERTY_borderPaint : String in class net.sf.jasperreports.chartthemes.simple.ChartSettings
Rename Parameter	chartBorderPaint : PaintProvider to borderPaint : PaintProvider in method public setBorderPaint(borderPaint PaintProvider) : void from class net.sf.jasperreports.chartthemes.simple.ChartSettings
Rename Attribute	chartBorderPaint : PaintProvider to borderPaint : PaintProvider in class net.sf.jasperreports.chartthemes.simple.ChartSettings
