### ISSUE TITLE
Timeout Exception davidmoten/rtree 3dbb24d7

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#583]
https://github.com/LWJGL/lwjgl3/commit/3dbb24d76d70ab8f3dbc14074c8d1fdad46cbd90 timed out

```
134916128 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 3dbb24d76d70ab8f3dbc14074c8d1fdad46cbd90
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)

**Comment by victorgveloso** [comment]
More 63 commits of the same project fail due to timeout

https://github.com/LWJGL/lwjgl3/commit/6b16aa8ea640ac818d701eaa352270a3351a32d7
https://github.com/LWJGL/lwjgl3/commit/35d936bdbef213c953c6169345f8774354bff7f1
https://github.com/LWJGL/lwjgl3/commit/b077b1e0f71e490c12a8edda019503553aff9533
https://github.com/LWJGL/lwjgl3/commit/4e6713d5dfe416751534810c99d67b2c70ffde2c
https://github.com/LWJGL/lwjgl3/commit/18ef45b4eff5c27bfd3f487510f508c670aefef7
https://github.com/LWJGL/lwjgl3/commit/db827d767f02b1010c1530817c26ff9a64e45a11
https://github.com/LWJGL/lwjgl3/commit/94fe08d3c61b67922e8ddbb2c2b6b5c43369acc2
https://github.com/LWJGL/lwjgl3/commit/cef7b0365f72e3879af6e9c73839c0d32fb9450c
https://github.com/LWJGL/lwjgl3/commit/d0fcfd296f15a09f3d20a5ecc6854f5bd79bb62b
https://github.com/LWJGL/lwjgl3/commit/7dc6c020931c28c6f3ac210a71488e002d715894
https://github.com/LWJGL/lwjgl3/commit/f4c2b0b70c25ed3c9a36ed15adf0e21eaf71c29e
https://github.com/LWJGL/lwjgl3/commit/639b142ba81d0557db6c2b58e4333dcdde35ccd7
https://github.com/LWJGL/lwjgl3/commit/98afaf6f804d73bb1c0f057ecbc5d2df1eb1b495
https://github.com/LWJGL/lwjgl3/commit/6e7fdff0c0c9009c207849c0dc8241e9dca43464
https://github.com/LWJGL/lwjgl3/commit/eaa39da891e8a45bbe63e8d96f5b95be808fe6d0
https://github.com/LWJGL/lwjgl3/commit/879f47b607fd0ae5f85469c702d6a4da538e5777
https://github.com/LWJGL/lwjgl3/commit/1f4c4f0ab21434a1143eea817cc568f4703b860a
https://github.com/LWJGL/lwjgl3/commit/0c4a2bcdf53fd73f569832c928074ca1074d5fdd
https://github.com/LWJGL/lwjgl3/commit/6ed7d78439665b2ad18c95141c0475dbdbea10d6
https://github.com/LWJGL/lwjgl3/commit/efea04818091799aa928f2ff2cd9484d8dfef8eb
https://github.com/LWJGL/lwjgl3/commit/39134def57833a0c8265aa52a5e332f6260d1a5d
https://github.com/LWJGL/lwjgl3/commit/c5bab97e18e70d90a5e5f033f5af7ccf81cb9fbd
https://github.com/LWJGL/lwjgl3/commit/dfe0a6f2e49317993b90089c26b25138feb3f114
https://github.com/LWJGL/lwjgl3/commit/a057bc91b14d9e1f194325f7a3577b8a5b5034ee
https://github.com/LWJGL/lwjgl3/commit/4462415b5a01fba6c64f405eb0bedac4b3a980ed
https://github.com/LWJGL/lwjgl3/commit/729ca84ee5a58fefd84be6d9b9e7423362978544
https://github.com/LWJGL/lwjgl3/commit/4db39c98e29a01f8fa23bfe33e9b131fcf3e61be
https://github.com/LWJGL/lwjgl3/commit/6faf416ecdbfef01983d35135dd9a9d78032af98
https://github.com/LWJGL/lwjgl3/commit/483560e3cb884c484f6436b551e697c49f953c8b
https://github.com/LWJGL/lwjgl3/commit/0d24c686a6278e02ca6afaa66be603e726d8faf5
https://github.com/LWJGL/lwjgl3/commit/bb6f5a5c136a990bf606fa76fbba5987216f03d8
https://github.com/LWJGL/lwjgl3/commit/70bdd6d3f20a4ce395c48d8e9b518bf8121cebc9
https://github.com/LWJGL/lwjgl3/commit/bf1b9df0ae6a03ad63c052077216969e709e0d09
https://github.com/LWJGL/lwjgl3/commit/3ae6eddba388d9e22a20d7b62662244e28e9b7ee
https://github.com/LWJGL/lwjgl3/commit/7aa488453d81c39102e3531b738412192e8f54e1
https://github.com/LWJGL/lwjgl3/commit/33e8656a06f77c26e53ded7dfdfacbd564ed2181
https://github.com/LWJGL/lwjgl3/commit/cc892ba33b846d812f474742552627d799aa061c
https://github.com/LWJGL/lwjgl3/commit/1e4b3d63a1a28e57bedaa5194cc21b18f69087ea
https://github.com/LWJGL/lwjgl3/commit/ce56fc6c805ea671a4cf4e79abbd331688adfb6d
https://github.com/LWJGL/lwjgl3/commit/4474889fac5b6f3a39145d4ab746264407a9597c
https://github.com/LWJGL/lwjgl3/commit/8886b7e5eed31a662062e555248f79c0a9efb865
https://github.com/LWJGL/lwjgl3/commit/ce4306452a81a0abb02f53f6924c0791fec74f07
https://github.com/LWJGL/lwjgl3/commit/e313c67c209e0618f8710c9569e59f6031098d89
https://github.com/LWJGL/lwjgl3/commit/406e73d3366edda1e5b34969374db383100fcec9
https://github.com/LWJGL/lwjgl3/commit/70531d9fd03f7f146af17c972d03ae181bd5c389
https://github.com/LWJGL/lwjgl3/commit/423b4f8c3a2be5559b7b30b3308ce790abec5583
https://github.com/LWJGL/lwjgl3/commit/e4a6cc863f469ea8acfe3c2158f2c77d0c0aa95d
https://github.com/LWJGL/lwjgl3/commit/9f096f6fa7f404c1ab84f6b1945a6d8549888787
https://github.com/LWJGL/lwjgl3/commit/ad71f9591476ee6529ee54b593704d9793f65345
https://github.com/LWJGL/lwjgl3/commit/60c43b38d562f7800c4111c2c9cb4051e5820371
https://github.com/LWJGL/lwjgl3/commit/3cc86dd601b754bdec8b0d094ecf65650d499a79
https://github.com/LWJGL/lwjgl3/commit/d43397891447624147f0f888b15bc8e1f1d89b74
https://github.com/LWJGL/lwjgl3/commit/f7d6c68732b238bf7c99de72854d1036b5f8fe05
https://github.com/LWJGL/lwjgl3/commit/ff80890ee6116a3a7ab25317530ba86f1edd75cc
https://github.com/LWJGL/lwjgl3/commit/f57d550298b8bcb607658ad0aa9f693caac1c136
https://github.com/LWJGL/lwjgl3/commit/267aceeedcce0d2886dfafde030e9aad0a813628
https://github.com/LWJGL/lwjgl3/commit/2b0d10adcbfe1eea1fb9a2c17965e9432b2301cb
https://github.com/LWJGL/lwjgl3/commit/522bfd0454d282210e31d2bce2510dfa11a8dfb2
https://github.com/LWJGL/lwjgl3/commit/15cc62b5f853c14070aa0f75aee309c4df4c7b0f
https://github.com/LWJGL/lwjgl3/commit/3017b3c1a1525acea67a6a370fca3fdd40902dae
https://github.com/LWJGL/lwjgl3/commit/57221b86c72725ae362602063730dce607c9a039
https://github.com/LWJGL/lwjgl3/commit/93339097902ac14ee18d9ccfd5615e45fd64c46f
https://github.com/LWJGL/lwjgl3/commit/c1f1e89274b5dfd95a83fcec1507999e7fc98f94
