### ISSUE TITLE
Timeout Exception pmd/pmd 7eac745

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#584]
https://github.com/pmd/pmd/commit/7eac745cb536b569161311db5bc09ae6ccfdefc2 timed out
```
143738717 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 7eac745cb536b569161311db5bc09ae6ccfdefc2
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment]
@victorgveloso 
**FIXED**

Refactorings at 7eac745cb536b569161311db5bc09ae6ccfdefc2
Add Method Annotation	@Override in method public jjtAccept(visitor JavaParserVisitor, data Object) : Object from class net.sourceforge.pmd.lang.java.ast.ASTAnnotationTypeDeclaration
Change Variable Type	decl : ASTClassOrInterfaceBodyDeclaration to decl : ASTAnyTypeBodyDeclaration in method private findOperations(node ASTAnyTypeDeclaration, includeNested boolean) : List<ASTMethodOrConstructorDeclaration> from class net.sourceforge.pmd.lang.java.oom.ClassStats
Rename Attribute	version : MetricVersion to metricVersion : MetricVersion in class net.sourceforge.pmd.lang.java.oom.metrics.AbstractMetricTestRule
Change Attribute Access Modifier	protected to private in attribute private metricVersion : MetricVersion from class net.sourceforge.pmd.lang.java.oom.metrics.AbstractMetricTestRule
Extract Interface	net.sourceforge.pmd.lang.java.ast.ASTAnyTypeBodyDeclaration from classes [net.sourceforge.pmd.lang.java.ast.ASTAnnotationTypeMemberDeclaration, net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration]
Change Parameter Type	node : ASTImportDeclaration to node : ASTFieldDeclaration in method public visit(node ASTFieldDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTImportDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTFieldDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTPackageDeclaration to node : ASTExplicitConstructorInvocation in method public visit(node ASTExplicitConstructorInvocation, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTPackageDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTExplicitConstructorInvocation, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTEnumDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTEnumDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTAnnotationTypeDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTAnnotationTypeDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTFieldDeclaration to node : ASTContinueStatement in method public visit(node ASTContinueStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTFieldDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTContinueStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTMethodDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTMethodDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTConstructorDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTConstructorDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTLocalVariableDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTLocalVariableDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTIfStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTIfStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTWhileStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTWhileStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTSwitchStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTSwitchStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTStatementExpression, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTStatementExpression, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTExplicitConstructorInvocation to node : ASTBreakStatement in method public visit(node ASTBreakStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTExplicitConstructorInvocation, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTBreakStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTContinueStatement to node : ASTReturnStatement in method public visit(node ASTReturnStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTContinueStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTReturnStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTBreakStatement to node : ASTLocalVariableDeclaration in method public visit(node ASTLocalVariableDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTBreakStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTLocalVariableDeclaration, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Change Parameter Type	node : ASTReturnStatement to node : ASTStatementExpression in method public visit(node ASTStatementExpression, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTReturnStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTStatementExpression, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTDoStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTDoStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTForStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTForStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTSynchronizedStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTSynchronizedStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTCatchStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTCatchStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTThrowStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTThrowStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTFinallyStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTFinallyStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTLabeledStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTLabeledStatement, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTSwitchLabel, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTSwitchLabel, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
Move Method	public visit(node ASTInitializer, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.JavaNcssVisitor to public visit(node ASTInitializer, data Object) : Object from class net.sourceforge.pmd.lang.java.oom.metrics.visitors.DefaultNcssVisitor
