### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by T45K** [tsantalis/RefactoringMiner#60]
I use RefactoringMiner as a library in my Kotlin project.
When I run my project, it terminates because of NPE in RefactoringMiner.

RefactoringMiner Version: latest(`c5d78bd0fb3bd5446a3f4e0d9779cca25b9eb531`)
project: Apache Camel(https://github.com/apache/camel)
stacktrace:
```
WARN  o.r.r.GitHistoryRefactoringMinerImpl - Ignored revision 2b448aec3f7b28aa750ab9d5a9515ff9410060db due to error
java.lang.NullPointerException: null
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1269)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:143)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
Caused by: java.lang.NullPointerException
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1269)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
	... 3 more
```

**Comment by T45K** [comment]
Thanks!

**Comment by tsantalis** [comment]
The commit https://github.com/apache/camel/commit/2b448aec3f7b28aa750ab9d5a9515ff9410060db
contains the following refactorings:
**Replace Variable With Attribute** cacheName : String to resourceUid : String in method public deleteCaches() : void in class org.apache.camel.component.ignite.IgniteCacheTest
**Replace Variable With Attribute** name : String to resourceUid : String in method public deleteSets() : void in class org.apache.camel.component.ignite.IgniteIdGenTest
