### ISSUE TITLE
Timeout Exception apache/hive 4221699

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#607]
https://github.com/apache/camel/commit/42216997f7fcff1853524b03e3961ec5c21f3fd7 timed out
```
172663413 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 42216997f7fcff1853524b03e3961ec5c21f3fd7
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment]
@victorgveloso
The commit does not exist.

**Comment by victorgveloso** [comment]
@tsantalis 

I just checked the logs and inferring from previous messages, all issues from 595 to 607 should actually report failing commits from the apache/hive project.

So this commit should be found at https://github.com/apache/hive/commit/42216997f7fcff1853524b03e3961ec5c21f3fd7

**Comment by tsantalis** [comment]
370 changed files with 67,652 additions and 22,750 deletions.
