### ISSUE TITLE
NullPointerException in UMLOperationBodyMapper

### ISSUE THREAD

**Issue by T45K** [tsantalis/RefactoringMiner#62]
I use RefactoringMiner as a library in my Kotlin project.
When I run my project, it terminates because of NPE in RefactoringMiner.

RefactoringMiner Version: latest([2df5f8a](https://github.com/tsantalis/RefactoringMiner/commit/2df5f8a5be254e104ca14fafdc7b73d70fedd315))
project: Apache Poi(https://github.com/apache/poi)
stacktrace:
```
2019-10-11 10:10:11,862 [main] WARN  o.r.r.GitHistoryRefactoringMinerImpl - Ignored revision 20447793519a29a99662866451bb9512c4fea565 due to error
java.lang.NullPointerException: null
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1857)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1008)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:124)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMoves(UMLModelDiff.java:1756) 
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMovesIncludingRemovedClasses(UMLModelDiff.java:1676)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1301) 
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:143)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
Caused by: java.lang.NullPointerException
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1857)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1008)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:124)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMoves(UMLModelDiff.java:1756)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMovesIncludingRemovedClasses(UMLModelDiff.java:1676)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1301)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
	... 3 more
```

and I find the same error in [Closure Compiler](https://github.com/google/closure-compiler) (revision `658f807348d64c857834130d6c47f136331f2e18`)

**Comment by T45K** [comment]
Thanks!
