### ISSUE TITLE
Timeout Exception Azure/azure-sdk-for-java 6277171

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#621]
https://github.com/Azure/azure-sdk-for-java/commit/6277171a21886f2b41cfe9e8da57ecdd8d88bcc5 timed out
```
122166108 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 6277171a21886f2b41cfe9e8da57ecdd8d88bcc5
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment]
6,820 changed files with 987,088 additions and 58,395 deletions.

**Comment by tsantalis** [comment]
Finished in 30 seconds

Refactorings at 6277171a21886f2b41cfe9e8da57ecdd8d88bcc5
Move Source Folder	azure-cognitiveservices to cognitiveservices/data-plane
Move Source Folder	azure-media to mediaservices/data-plane
Move Source Folder	azure-eventgrid to eventgrid/data-plane
