### ISSUE TITLE
Timeout Exception apache/hive 9320838

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#631]
https://github.com/apache/hive/commit/93208383964cc3ed5bdf4088f13fd13ecdec6c2c timed out
```
124448952 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 93208383964cc3ed5bdf4088f13fd13ecdec6c2c
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment]
Finished in 5 seconds

Refactorings at 93208383964cc3ed5bdf4088f13fd13ecdec6c2c
Extract Variable	attributeIdentifier : String in method private getStructTypeStringFromAST(typeNode ASTNode) : String from class org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer
