### ISSUE TITLE
NPE apache/kafka 839e75a

### ISSUE THREAD

**Issue by Xiaoven** [tsantalis/RefactoringMiner#651]
refactoringMiner version: `com.github.tsantalis:refactoring-miner:3.0.4`

NPE thrown while analyzing https://github.com/apache/kafka/commit/839e75a72968b697b05c6265219fc3bba583dd40

```
[main] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision 839e75a72968b697b05c6265219fc3bba583dd40 due to error
java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.CompositeStatementObject.getParent()" because the return value of "gr.uom.java.xmi.decomposition.AbstractCodeFragment.getParent()" is null
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.existsMappingSubsumingBoth(UMLOperationBodyMapper.java:764)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:731)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.updateMapperSet(UMLClassBaseDiff.java:1500)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:911)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:112)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:115)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:568)
	at Kafka.analysisAllCommit(Kafka.java:35)
	at Kafka.main(Kafka.java:77)
```

**Comment by tsantalis** [comment]
@Xiaoven 
Thank you for your bug report. The issue has been fixed and will be included in the next release 3.0.5.
