### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by boyang9602** [tsantalis/RefactoringMiner#71]
Hi
I met StringOutOfBoundsException at [bfcc17f211834710add79122d7ba3d267931cfb1](https://github.com/apache/kafka/commit/bfcc17f211834710add79122d7ba3d267931cfb1). 
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -5

	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.UMLType.extractTypeObject(UMLType.java:234)
	at gr.uom.java.xmi.decomposition.OperationInvocation.matchesOperation(OperationInvocation.java:142)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForExtractedAndMovedOperations(UMLModelDiff.java:1545)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1328)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
	at Project.detect(Project.java:93)
	at Detector.run(Detector.java:20)
```

**Comment by tsantalis** [comment]
Unable to replicate the bug with the latest code

**Comment by boyang9602** [comment]
> Unable to replicate the bug with the latest code

yes, it does not occur in the latest code. But I'm not sure if it was solved correctly.  
This is the code caused the exception: https://github.com/apache/kafka/commit/bfcc17f211834710add79122d7ba3d267931cfb1#diff-144828fa7b2d4d2c9e9075e0e9bd00afL165  
```java
new Object[]{"test", "name", "test/test", "test\u1234", "\u1324name\\", "/+%>&):??<&()?-", "+1", "\uD83D\uDE01", "\uF3B1", "     test   \n\r", "\n  hello \t"},
```
I think it was prevented by this commit: https://github.com/tsantalis/RefactoringMiner/commit/d93f77b2aac1b22c733adb372f7e246fafd6a4ef#diff-05db52f84e2bad21b2f6fb54dc6999d8R128  
But I don't think this is a "concatenate string literals" type. So I am not sure if this commit solved the problem correctly. Could you please check it again? Thank you.
