### ISSUE TITLE
NullPointerException for UMLModelDiff at specific commit

### ISSUE THREAD

**Issue by SteveLocke** [tsantalis/RefactoringMiner#73]
Project: https://github.com/apache/incubator-druid
Commit: https://github.com/apache/incubator-druid/commit/fa7cb906e40021549648848caada38cf80338b7b
Summary: I receive the following exception on 2 separate runs for all commits in master branch using -a therefore the issue is reproducible. The stack traces for the two runs are listed below
Additional Notes: May be related to or fixed by #70. I see that fix was made 5 days ago

Stacktrace 1:

...
No refactorings found in commit e8ddd9942d2bfa53d676eb94b93f0e80e40821c0
No refactorings found in commit 114a9fc38feda5f85799d24889007bc572d04dea
No refactorings found in commit 67f832957b06429259aeed2054f4e824db42db26
Error processing commit fa7cb906e40021549648848caada38cf80338b7b
java.lang.NullPointerException
        at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1247)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
        at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:67)
        at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)

Stacktrace 2:

...
No refactorings found in commit 114a9fc38feda5f85799d24889007bc572d04dea
No refactorings found in commit 67f832957b06429259aeed2054f4e824db42db26
Error processing commit fa7cb906e40021549648848caada38cf80338b7b
java.lang.NullPointerException
        at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:1247)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:182)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:138)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
        at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:67)
        at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)

**Comment by tsantalis** [comment]
Unable to replicate the exception.
