### ISSUE TITLE
Allow `/files` URL

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#757]
I tried https://github.com/JabRef/jabref/pull/11486/files as URL (to double check that Markdown is not supported; other story)

I got

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "11486/files"
        at gui.webdiff.WebDiffRunner.execute(WebDiffRunner.java:74)
        at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:49)
```

Refs https://github.com/tsantalis/RefactoringMiner/issues/756

**Comment by tsantalis** [comment]
I think this is redundant, just omitting `/files` works.

**Comment by koppor** [comment]
Its for people just wanting copy and paste from the browser while reviewing. They don't want to think how to adapt the URL shown by the browser. - If I find time, I maybe submit a PR. 😅

**Comment by tsantalis** [comment]
@koppor 
OK, I fixed it.
