### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by johanneshaertel** [tsantalis/RefactoringMiner#77]
On repository https://github.com/MinecraftForge/MinecraftForge executing-a C:\Data\Corpus\Repositories\MinecraftForge 1.14.x:

Error processing commit 93025510aec90cb89c4bc24eb8759a4aa5f6e215
java.lang.NullPointerException at 
gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1890)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1052)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:127)
	at gr.uom.java.xmi.diff.UMLClassDiff.createBodyMappers(UMLClassDiff.java:113)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:95)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:147)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:183)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:139)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:391)
	at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:67)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33)

(also happening at: 0e9820c51c1720bf8d49bd1431de06829ae6dc8d, e3777f455991b6803eb826ff6305d17749462a3b, 4b53f0716b3b33a70f51fabe8a0c72cedded2087, 5445f9632700385b26fc7c320b32b84dbf4570b7 and c545b8ecd4e96107ccf134c8fd89906357d586ad)

**Comment by johanneshaertel** [comment]
Working, thanks!
