### ISSUE TITLE
IndexOutOfBoundsException on detectAtCommit()

### ISSUE THREAD

**Issue by mo7aammd** [tsantalis/RefactoringMiner#778]
https://github.com/apache/cassandra/commit/cb56d9fc3c773abbefa2044ce41ddbfb7717e0cb
-----------------------------------------------------------------------------------------------------------
Error => java.lang.IndexOutOfBoundsException: Index -9 out of bounds for length 6
-----------------------------------------------------------------------------------------------------------
[main] INFO org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Processing tmp\cassandra cb56d9fc3c773abbefa2044ce41ddbfb7717e0cb ...
[main] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision cb56d9fc3c773abbefa2044ce41ddbfb7717e0cb due to error
java.lang.IndexOutOfBoundsException: Index -9 out of bounds for length 6
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at gr.uom.java.xmi.diff.UMLJavadocDiff.processModifiedTags(UMLJavadocDiff.java:279)
	at gr.uom.java.xmi.diff.UMLJavadocDiff.<init>(UMLJavadocDiff.java:111)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:975)
Error => java.lang.IndexOutOfBoundsException: Index -9 out of bounds for length 6
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.createBodyMappers(UMLClassBaseDiff.java:3003)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:162)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:163)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:801)

**Comment by tsantalis** [comment]
Thank you @mo7aammd 
The exception is on newly added code that was not so thoroughly tested.
I will work to fix the problem.

**Comment by tsantalis** [comment]
@mo7aammd 
Thank you for reporting this issue. I was able to fix it in a reliable way, and I will make a new release soon.

**Comment by tsantalis** [comment]
@mo7aammd 
New release 7.0.9 is available in Maven

**Comment by mo7aammd** [comment]
Thank you, I appreciate the quick response
