### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by a-fujimt** [tsantalis/RefactoringMiner#80]
I use RefactoringMiner to Java project dnsJava(https://github.com/dnsjava/dnsjava).
In some commits, RefactoringMiner throws StringIndexOutOfBoundsException.

This is the Exception Stack Trace.

```
Error processing commit c3f00c041cfc96afed6a6a7380a80ce31f854446
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.populateFileContents(GitHistoryRefactoringMinerImpl.java:213)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:177)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:139)
        at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:390)
        at org.refactoringminer.RefactoringMiner.detectAll(RefactoringMiner.java:67)
        at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:33))
```

Maybe, if `.java` file exists in project's root directory, RefactoringMiner throws the exception.

**Comment by tsantalis** [comment]
Thanks @a-fujimt 
The bug is fixed.
