### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded when detecting a specific commit of hadoop.

### ISSUE THREAD

**Issue by holen-zhang** [tsantalis/RefactoringMiner#93]
Hi,

Thanks for providing this excellent tool. I am using RefactoringMiner to detect the refactorings in Hadoop and I want to report a bug.

At first I tried to detect all the commits of Hadoop but it stuck in the commit [6ade9e6ce6019d2d347cbda6b968bf6950403c12](https://github.com/apache/hadoop/commit/6ade9e6ce6019d2d347cbda6b968bf6950403c12) for a long time and the  _java.lang.OutOfMemoryError_ is reported. The error message is as follows:
```
Processing commit: 6ade9e6ce6019d2d347cbda6b968bf6950403c12
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at gr.uom.java.xmi.decomposition.ReplacementUtil.performReplacement(ReplacementUtil.java:61)
	at gr.uom.java.xmi.decomposition.AbstractCall.update(AbstractCall.java:430)
	at gr.uom.java.xmi.decomposition.OperationInvocation.update(OperationInvocation.java:124)
	at gr.uom.java.xmi.decomposition.OperationInvocation.update(OperationInvocation.java:28)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.replaceVariablesWithArguments(UMLOperationBodyMapper.java:3711)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1674)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1163)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:127)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.updateMapperSet(UMLClassBaseDiff.java:1098)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:1016)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:99)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:147)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:140)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:366)
```

Then I tried to detect only this commit but got a similar error. The full error message is as follows:
```
Processing commit: 6ade9e6ce6019d2d347cbda6b968bf6950403c12
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:472)
	at java.lang.StringBuffer.append(StringBuffer.java:310)
	at java.lang.StringBuffer.append(StringBuffer.java:97)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:486)
	at java.lang.StringBuffer.append(StringBuffer.java:338)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:890)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replace(String.java:2240)
	at gr.uom.java.xmi.decomposition.ReplacementUtil.performArgumentReplacement(ReplacementUtil.java:47)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.replaceVariablesWithArguments(UMLOperationBodyMapper.java:3705)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1674)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:1163)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:127)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.updateMapperSet(UMLClassBaseDiff.java:1106)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:1024)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:102)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:147)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:140)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:366)
```
Maybe there is something special in this commit that makes RefactoringMiner crash?

**Reproduce:**
Detecting the commit 6ade9e6ce6019d2d347cbda6b968bf6950403c12 of Hadoop.

Update:
Same error reported for the commit [87e2ef8c985bb72a916477e8783359f2859f7890](https://github.com/apache/hadoop/commit/87e2ef8c985bb72a916477e8783359f2859f7890).

**Comment by tsantalis** [comment]
@holen-zhang Thank you for the bug report. It has been fixed.

**Comment by holen-zhang** [comment]
Thanks very much for your quick fix, it's working perfectly now!
