### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by zakiournani** [tsantalis/RefactoringMiner#94]
Hello, 
I am trying to run the example of the readme file to get to know this tool and use it in my further studies, so I'm running the following : 
```
public static void main(String[] args) throws Exception {
		GitService gitService = new GitServiceImpl();
		GitHistoryRefactoringMiner miner = new GitHistoryRefactoringMinerImpl();

		Repository repo = null;
		try {
			repo = gitService.cloneIfNotExists(
			    "/tmp/refactoring-toy-example",
			    "https://github.com/danilofes/refactoring-toy-example.git");
		} catch (Exception e) {
			e.printStackTrace();
		}

		miner.detectAll(repo, "master", new RefactoringHandler() {
		  @Override
		  public void handle(String commitId, List<Refactoring> refactorings) {
		    System.out.println("Refactorings at " + commitId);
		    for (Refactoring ref : refactorings) {
		      System.out.println(ref.toString());
		    }
		  }
		});
	
	}
```
However, i keep on encountering this error that i cannot figure-out its cause, Am i doing something wrong ? 

Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:101)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:325)
	at Main.main(Main.java:26)
Caused by: java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:235)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:131)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:64)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.createModel(GitHistoryRefactoringMinerImpl.java:348)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:135)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:96)

	
Thank you.

**Comment by tsantalis** [comment]
I am not able to replicate this exception, and I never experienced a similar issue before.
It takes place in class ASTParser from Eclipse JDT.
@zakiournani How exactly do you execute RefactoringMiner?

**Comment by zakiournani** [comment]
Thank you for your answer,
I have tried to use it by building the JAR and add it to the class-path of an Eclipse project with the other dependency JARs (jgit, slf4j, commons-io, eclipse.jdt.core, ... ).
for now i am using the CLI version that works but is less appropriate to use within a source code.

**Comment by tsantalis** [comment]
Did you try this way to add it in your project?
https://github.com/tsantalis/RefactoringMiner#how-to-use-refactoringminer-as-a-maven-dependency
